export const SET_PROBLEM_PHOTO = "SET_PROBLEM_PHOTO";
export const SET_PROBLEM_CATEGORY= "SET_PROBLEM_CATEGORY";
export const SET_PROBLEM = "SET_PROBLEM";
export const SET_PROBLEM_DESCRIPTION = "SET_PROBLEM_DESCRIPTION";
export const SET_PROBLEM_LOCATION = "SET_PROBLEM_LOCATION";
export const CLEAR_PROBLEM = "CLEAR_PROBLEM";